### ISSUE TITLE
Create variable for latest visible time

### ISSUE THREAD

**Issue by RomainGehrig** [ml729/calfw-blocks#6]
Many thanks for the package, it's finally a day/week planner I can use in Emacs :+1: 

My only grip is that the hour-by-hour view (`'block-day`,`'block-week`,...) is too tall and the view scrolls to the bottom when I open the calendar or change date. Would it be possible to add a variable like `calfw-blocks-earliest-visible-time` to set the last visible hour?

(Also, when I set `calfw-blocks-earliest-visible-time` to `(7 0)` and it makes the last hour of the day 6am.)

**Comment by ml729** [comment]
Glad to hear you like it.

There is an existing variable `calfw-blocks-initial-visible-time`, the intended functionality (and the one I see on my end) is that whenever you open the calendar or change the date, it should automatically scroll so that the top of the screen is `calfw-blocks-initial-visible-time`. The default for `calfw-blocks-initial-visible-time` is `(8 0)`.

To clarify, are you saying that this does not happen for you (and instead it always scrolls to the bottom of the buffer)?

**Comment by RomainGehrig** [comment]
Thanks for telling me about `calfw-blocks-initial-visible-time`! I played a bit with it and found that I need to set `calfw-blocks-initial-visible-time` to `(0 0)` so the buffer does not scroll down when `calfw-blocks-earliest-visible-time` is `(7 0)`. 

The scrolling was my main bother so I don't really need a variable to set the latest visible time if `calfw-blocks-initial-visible-time` solves this!

Closing the issue
